export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const CREATE_CHATROOM = "CREATE_CHATROOM";
export const CREATE_CHATROOM_SUCCESS = "CREATE_CHATROOM_SUCCESS";
export const CREATE_CHATROOM_FAILED = "CREATE_CHATROOM_FAILED";

export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILED = "FETCH_MESSAGES_FAILED";

export const FETCH_CHATROOMS = "FETCH_CHATROOMS";
export const FETCH_CHATROOMS_SUCCESS = "FETCH_CHATROOMS_SUCCESS";
export const FETCH_CHATROOMS_FAILED = "FETCH_CHATROOMS_FAILED";

export const NONE = "NONE";
export const SET_CURRENT_CHATID = "SET_CURRENT_CHATID";
