/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0da4de11-490a-4423-9792-90cce129898b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RU2DemGqO",
    "aws_user_pools_web_client_id": "64rs7lk278f52d5iij1rvn95as",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://am57it2aurg3riw3fandmdvrjq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
